//bitbucket.org/atlassian/atlaskit-mk-2/raw/4ad0e56649c3e6c973e226b7efaeb28cb240ccb0/packages/core/select/src/data/countries.js

// @flow

module.exports = [
  { icon: '🇦🇫', name: 'Afghanistan', iso2: 'AF', code: '93' },
  { icon: '🇦🇽', name: 'Alland Islands', iso2: 'AX', code: '358' },
  { icon: '🇦🇱', name: 'Albania', iso2: 'AL', code: '355' },
  { icon: '🇩🇿', name: 'Algeria', iso2: 'DZ', code: '213' },
  { icon: '🇦🇸', name: 'American Samoa', iso2: 'AS', code: '1-684' },
  { icon: '🇦🇩', name: 'Andorra', iso2: 'AD', code: '376' },
  { icon: '🇦🇴', name: 'Angola', iso2: 'AO', code: '244' },
  { icon: '🇦🇮', name: 'Anguilla', iso2: 'AI', code: '1-264' },
  { icon: '🇦🇶', name: 'Antarctica', iso2: 'AQ', code: '672' },
  { icon: '🇦🇬', name: 'Antigua and Barbuda', iso2: 'AG', code: '1-268' },
  { icon: '🇦🇷', name: 'Argentina', iso2: 'AR', code: '54' },
  { icon: '🇦🇲', name: 'Armenia', iso2: 'AM', code: '374' },
  { icon: '🇦🇼', name: 'Aruba', iso2: 'AW', code: '297' },
  { icon: '🇦🇺', name: 'Australia', iso2: 'AU', code: '61', suggested: true },
  { icon: '🇦🇹', name: 'Austria', iso2: 'AT', code: '43' },
  { icon: '🇦🇿', name: 'Azerbaijan', iso2: 'AZ', code: '994' },
  { icon: '🇧🇸', name: 'Bahamas', iso2: 'BS', code: '1-242' },
  { icon: '🇧🇭', name: 'Bahrain', iso2: 'BH', code: '973' },
  { icon: '🇧🇩', name: 'Bangladesh', iso2: 'BD', code: '880' },
  { icon: '🇧🇧', name: 'Barbados', iso2: 'BB', code: '1-246' },
  { icon: '🇧🇾', name: 'Belarus', iso2: 'BY', code: '375' },
  { icon: '🇧🇪', name: 'Belgium', iso2: 'BE', code: '32' },
  { icon: '🇧🇿', name: 'Belize', iso2: 'BZ', code: '501' },
  { icon: '🇧🇯', name: 'Benin', iso2: 'BJ', code: '229' },
  { icon: '🇧🇲', name: 'Bermuda', iso2: 'BM', code: '1-441' },
  { icon: '🇧🇹', name: 'Bhutan', iso2: 'BT', code: '975' },
  { icon: '🇧🇴', name: 'Bolivia', iso2: 'BO', code: '591' },
  { icon: '🇧🇦', name: 'Bosnia and Herzegovina', iso2: 'BA', code: '387' },
  { icon: '🇧🇼', name: 'Botswana', iso2: 'BW', code: '267' },
  { icon: '🇧🇻', name: 'Bouvet Island', iso2: 'BV', code: '47' },
  { icon: '🇧🇷', name: 'Brazil', iso2: 'BR', code: '55' },
  {
    icon: '🇮🇴',
    name: 'British Indian Ocean Territory',
    iso2: 'IO',
    code: '246',
  },
  { icon: '🇻🇬', name: 'British Virgin Islands', iso2: 'VG', code: '1-284' },
  { icon: '🇧🇳', name: 'Brunei Darussalam', iso2: 'BN', code: '673' },
  { icon: '🇧🇬', name: 'Bulgaria', iso2: 'BG', code: '359' },
  { icon: '🇧🇫', name: 'Burkina Faso', iso2: 'BF', code: '226' },
  { icon: '🇧🇮', name: 'Burundi', iso2: 'BI', code: '257' },
  { icon: '🇰🇭', name: 'Cambodia', iso2: 'KH', code: '855' },
  { icon: '🇨🇲', name: 'Cameroon', iso2: 'CM', code: '237' },
  { icon: '🇨🇦', name: 'Canada', iso2: 'CA', code: '1', suggested: true },
  { icon: '🇨🇻', name: 'Cape Verde', iso2: 'CV', code: '238' },
  { icon: '🇰🇾', name: 'Cayman Islands', iso2: 'KY', code: '1-345' },
  { icon: '🇨🇫', name: 'Central African Republic', iso2: 'CF', code: '236' },
  { icon: '🇹🇩', name: 'Chad', iso2: 'TD', code: '235' },
  { icon: '🇨🇱', name: 'Chile', iso2: 'CL', code: '56' },
  { icon: '🇨🇳', name: 'China', iso2: 'CN', code: '86' },
  { icon: '🇨🇽', name: 'Christmas Island', iso2: 'CX', code: '61' },
  { icon: '🇨🇨', name: 'Cocos (Keeling) Islands', iso2: 'CC', code: '61' },
  { icon: '🇨🇴', name: 'Colombia', iso2: 'CO', code: '57' },
  { icon: '🇰🇲', name: 'Comoros', iso2: 'KM', code: '269' },
  {
    icon: '🇨🇩',
    name: 'Congo, Democratic Republic of the',
    iso2: 'CG',
    code: '243',
  },
  {
    icon: '🇨🇬',
    name: 'Congo, Republic of the',
    iso2: 'CD',
    code: '242',
  },
  { icon: '🇨🇰', name: 'Cook Islands', iso2: 'CK', code: '682' },
  { icon: '🇨🇷', name: 'Costa Rica', iso2: 'CR', code: '506' },
  { icon: '🇨🇮', name: "Cote d'Ivoire", iso2: 'CI', code: '225' },
  { icon: '🇭🇷', name: 'Croatia', iso2: 'HR', code: '385' },
  { icon: '🇨🇺', name: 'Cuba', iso2: 'CU', code: '53' },
  { icon: '🇨🇼', name: 'Curacao', iso2: 'CW', code: '599' },
  { icon: '🇨🇾', name: 'Cyprus', iso2: 'CY', code: '357' },
  { icon: '🇨🇿', name: 'Czech Republic', iso2: 'CZ', code: '420' },
  { icon: '🇩🇰', name: 'Denmark', iso2: 'DK', code: '45' },
  { icon: '🇩🇯', name: 'Djibouti', iso2: 'DJ', code: '253' },
  { icon: '🇩🇲', name: 'Dominica', iso2: 'DM', code: '1-767' },
  { icon: '🇩🇴', name: 'Dominican Republic', iso2: 'DO', code: '1-809' },
  { icon: '🇪🇨', name: 'Ecuador', iso2: 'EC', code: '593' },
  { icon: '🇪🇬', name: 'Egypt', iso2: 'EG', code: '20' },
  { icon: '🇸🇻', name: 'El Salvador', iso2: 'SV', code: '503' },
  { icon: '🇬🇶', name: 'Equatorial Guinea', iso2: 'GQ', code: '240' },
  { icon: '🇪🇷', name: 'Eritrea', iso2: 'ER', code: '291' },
  { icon: '🇪🇪', name: 'Estonia', iso2: 'EE', code: '372' },
  { icon: '🇪🇹', name: 'Ethiopia', iso2: 'ET', code: '251' },
  { icon: '🇫🇰', name: 'Falkland Islands (Malvinas)', iso2: 'FK', code: '500' },
  { icon: '🇫🇴', name: 'Faroe Islands', iso2: 'FO', code: '298' },
  { icon: '🇫🇯', name: 'Fiji', iso2: 'FJ', code: '679' },
  { icon: '🇫🇮', name: 'Finland', iso2: 'FI', code: '358' },
  { icon: '🇫🇷', name: 'France', iso2: 'FR', code: '33', suggested: true },
  { icon: '🇬🇫', name: 'French Guiana', iso2: 'GF', code: '594' },
  { icon: '🇵🇫', name: 'French Polynesia', iso2: 'PF', code: '689' },
  { icon: '🇹🇫', name: 'French Southern Territories', iso2: 'TF', code: '262' },
  { icon: '🇬🇦', name: 'Gabon', iso2: 'GA', code: '241' },
  { icon: '🇬🇲', name: 'Gambia', iso2: 'GM', code: '220' },
  { icon: '🇬🇪', name: 'Georgia', iso2: 'GE', code: '995' },
  { icon: '🇩🇪', name: 'Germany', iso2: 'DE', code: '49', suggested: true },
  { icon: '🇬🇭', name: 'Ghana', iso2: 'GH', code: '233' },
  { icon: '🇬🇮', name: 'Gibraltar', iso2: 'GI', code: '350' },
  { icon: '🇬🇷', name: 'Greece', iso2: 'GR', code: '30' },
  { icon: '🇬🇱', name: 'Greenland', iso2: 'GL', code: '299' },
  { icon: '🇬🇩', name: 'Grenada', iso2: 'GD', code: '1-473' },
  { icon: '🇬🇵', name: 'Guadeloupe', iso2: 'GP', code: '590' },
  { icon: '🇬🇺', name: 'Guam', iso2: 'GU', code: '1-671' },
  { icon: '🇬🇹', name: 'Guatemala', iso2: 'GT', code: '502' },
  { icon: '🇬🇬', name: 'Guernsey', iso2: 'GG', code: '44' },
  { icon: '🇬🇼', name: 'Guinea-Bissau', iso2: 'GW', code: '245' },
  { icon: '🇬🇳', name: 'Guinea', iso2: 'GN', code: '224' },
  { icon: '🇬🇾', name: 'Guyana', iso2: 'GY', code: '592' },
  { icon: '🇭🇹', name: 'Haiti', iso2: 'HT', code: '509' },
  {
    icon: '🇭🇲',
    name: 'Heard Island and McDonald Islands',
    iso2: 'HM',
    code: '672',
  },
  {
    icon: '🇻🇦',
    name: 'Holy See (Vatican City State)',
    iso2: 'VA',
    code: '379',
  },
  { icon: '🇭🇳', name: 'Honduras', iso2: 'HN', code: '504' },
  { icon: '🇭🇰', name: 'Hong Kong', iso2: 'HK', code: '852' },
  { icon: '🇭🇺', name: 'Hungary', iso2: 'HU', code: '36' },
  { icon: '🇮🇸', name: 'Iceland', iso2: 'IS', code: '354' },
  { icon: '🇮🇳', name: 'India', iso2: 'IN', code: '91' },
  { icon: '🇮🇩', name: 'Indonesia', iso2: 'ID', code: '62' },
  { icon: '🇮🇷', name: 'Iran, Islamic Republic of', iso2: 'IR', code: '98' },
  { icon: '🇮🇶', name: 'Iraq', iso2: 'IQ', code: '964' },
  { icon: '🇮🇪', name: 'Ireland', iso2: 'IE', code: '353' },
  { icon: '🇮🇲', name: 'Isle of Man', iso2: 'IM', code: '44' },
  { icon: '🇮🇱', name: 'Israel', iso2: 'IL', code: '972' },
  { icon: '🇮🇹', name: 'Italy', iso2: 'IT', code: '39' },
  { icon: '🇯🇲', name: 'Jamaica', iso2: 'JM', code: '1-876' },
  { icon: '🇯🇵', name: 'Japan', iso2: 'JP', code: '81', suggested: true },
  { icon: '🇯🇪', name: 'Jersey', iso2: 'JE', code: '44' },
  { icon: '🇯🇴', name: 'Jordan', iso2: 'JO', code: '962' },
  { icon: '🇰🇿', name: 'Kazakhstan', iso2: 'KZ', code: '7' },
  { icon: '🇰🇪', name: 'Kenya', iso2: 'KE', code: '254' },
  { icon: '🇰🇮', name: 'Kiribati', iso2: 'KI', code: '686' },
  {
    icon: '🇰🇵',
    name: "Korea, Democratic People's Republic of",
    iso2: 'KP',
    code: '850',
  },
  { icon: '🇰🇷', name: 'Korea, Republic of', iso2: 'KR', code: '82' },
  { icon: '🇽🇰', name: 'Kosovo', iso2: 'XK', code: '383' },
  { icon: '🇰🇼', name: 'Kuwait', iso2: 'KW', code: '965' },
  { icon: '🇰🇬', name: 'Kyrgyzstan', iso2: 'KG', code: '996' },
  {
    icon: '🇱🇦',
    name: "Lao People's Democratic Republic",
    iso2: 'LA',
    code: '856',
  },
  { icon: '🇱🇻', name: 'Latvia', iso2: 'LV', code: '371' },
  { icon: '🇱🇧', name: 'Lebanon', iso2: 'LB', code: '961' },
  { icon: '🇱🇸', name: 'Lesotho', iso2: 'LS', code: '266' },
  { icon: '🇱🇷', name: 'Liberia', iso2: 'LR', code: '231' },
  { icon: '🇱🇾', name: 'Libya', iso2: 'LY', code: '218' },
  { icon: '🇱🇮', name: 'Liechtenstein', iso2: 'LI', code: '423' },
  { icon: '🇱🇹', name: 'Lithuania', iso2: 'LT', code: '370' },
  { icon: '🇱🇺', name: 'Luxembourg', iso2: 'LU', code: '352' },
  { icon: '🇲🇴', name: 'Macao', iso2: 'MO', code: '853' },
  {
    icon: '🇲🇰',
    name: 'Macedonia, the Former Yugoslav Republic of',
    iso2: 'MK',
    code: '389',
  },
  { icon: '🇲🇬', name: 'Madagascar', iso2: 'MG', code: '261' },
  { icon: '🇲🇼', name: 'Malawi', iso2: 'MW', code: '265' },
  { icon: '🇲🇾', name: 'Malaysia', iso2: 'MY', code: '60' },
  { icon: '🇲🇻', name: 'Maldives', iso2: 'MV', code: '960' },
  { icon: '🇲🇱', name: 'Mali', iso2: 'ML', code: '223' },
  { icon: '🇲🇹', name: 'Malta', iso2: 'MT', code: '356' },
  { icon: '🇲🇭', name: 'Marshall Islands', iso2: 'MH', code: '692' },
  { icon: '🇲🇶', name: 'Martinique', iso2: 'MQ', code: '596' },
  { icon: '🇲🇷', name: 'Mauritania', iso2: 'MR', code: '222' },
  { icon: '🇲🇺', name: 'Mauritius', iso2: 'MU', code: '230' },
  { icon: '🇾🇹', name: 'Mayotte', iso2: 'YT', code: '262' },
  { icon: '🇲🇽', name: 'Mexico', iso2: 'MX', code: '52' },
  {
    icon: '🇫🇲',
    name: 'Micronesia, Federated States of',
    iso2: 'FM',
    code: '691',
  },
  { icon: '🇲🇩', name: 'Moldova, Republic of', iso2: 'MD', code: '373' },
  { icon: '🇲🇨', name: 'Monaco', iso2: 'MC', code: '377' },
  { icon: '🇲🇳', name: 'Mongolia', iso2: 'MN', code: '976' },
  { icon: '🇲🇪', name: 'Montenegro', iso2: 'ME', code: '382' },
  { icon: '🇲🇸', name: 'Montserrat', iso2: 'MS', code: '1-664' },
  { icon: '🇲🇦', name: 'Morocco', iso2: 'MA', code: '212' },
  { icon: '🇲🇿', name: 'Mozambique', iso2: 'MZ', code: '258' },
  { icon: '🇲🇲', name: 'Myanmar', iso2: 'MM', code: '95' },
  { icon: '🇳🇦', name: 'Namibia', iso2: 'NA', code: '264' },
  { icon: '🇳🇷', name: 'Nauru', iso2: 'NR', code: '674' },
  { icon: '🇳🇵', name: 'Nepal', iso2: 'NP', code: '977' },
  { icon: '🇳🇱', name: 'Netherlands', iso2: 'NL', code: '31' },
  { icon: '🇳🇨', name: 'New Caledonia', iso2: 'NC', code: '687' },
  { icon: '🇳🇿', name: 'New Zealand', iso2: 'NZ', code: '64' },
  { icon: '🇳🇮', name: 'Nicaragua', iso2: 'NI', code: '505' },
  { icon: '🇳🇪', name: 'Niger', iso2: 'NE', code: '227' },
  { icon: '🇳🇬', name: 'Nigeria', iso2: 'NG', code: '234' },
  { icon: '🇳🇺', name: 'Niue', iso2: 'NU', code: '683' },
  { icon: '🇳🇫', name: 'Norfolk Island', iso2: 'NF', code: '672' },
  { icon: '🇲🇵', name: 'Northern Mariana Islands', iso2: 'MP', code: '1-670' },
  { icon: '🇳🇴', name: 'Norway', iso2: 'NO', code: '47' },
  { icon: '🇴🇲', name: 'Oman', iso2: 'OM', code: '968' },
  { icon: '🇵🇰', name: 'Pakistan', iso2: 'PK', code: '92' },
  { icon: '🇵🇼', name: 'Palau', iso2: 'PW', code: '680' },
  { icon: '🇵🇸', name: 'Palestine, State of', iso2: 'PS', code: '970' },
  { icon: '🇵🇦', name: 'Panama', iso2: 'PA', code: '507' },
  { icon: '🇵🇬', name: 'Papua New Guinea', iso2: 'PG', code: '675' },
  { icon: '🇵🇾', name: 'Paraguay', iso2: 'PY', code: '595' },
  { icon: '🇵🇪', name: 'Peru', iso2: 'PE', code: '51' },
  { icon: '🇵🇭', name: 'Philippines', iso2: 'PH', code: '63' },
  { icon: '🇵🇳', name: 'Pitcairn', iso2: 'PN', code: '870' },
  { icon: '🇵🇱', name: 'Poland', iso2: 'PL', code: '48' },
  { icon: '🇵🇹', name: 'Portugal', iso2: 'PT', code: '351' },
  { icon: '🇵🇷', name: 'Puerto Rico', iso2: 'PR', code: '1' },
  { icon: '🇶🇦', name: 'Qatar', iso2: 'QA', code: '974' },
  { icon: '🇷🇪', name: 'Reunion', iso2: 'RE', code: '262' },
  { icon: '🇷🇴', name: 'Romania', iso2: 'RO', code: '40' },
  { icon: '🇷🇺', name: 'Russian Federation', iso2: 'RU', code: '7' },
  { icon: '🇷🇼', name: 'Rwanda', iso2: 'RW', code: '250' },
  { icon: '🇧🇱', name: 'Saint Barthelemy', iso2: 'BL', code: '590' },
  { icon: '🇸🇭', name: 'Saint Helena', iso2: 'SH', code: '290' },
  { icon: '🇰🇳', name: 'Saint Kitts and Nevis', iso2: 'KN', code: '1-869' },
  { icon: '🇱🇨', name: 'Saint Lucia', iso2: 'LC', code: '1-758' },
  { icon: '🇲🇫', name: 'Saint Martin (French part)', iso2: 'MF', code: '590' },
  { icon: '🇵🇲', name: 'Saint Pierre and Miquelon', iso2: 'PM', code: '508' },
  {
    icon: '🇻🇨',
    name: 'Saint Vincent and the Grenadines',
    iso2: 'VC',
    code: '1-784',
  },
  { icon: '🇼🇸', name: 'Samoa', iso2: 'WS', code: '685' },
  { icon: '🇸🇲', name: 'San Marino', iso2: 'SM', code: '378' },
  { icon: '🇸🇹', name: 'Sao Tome and Principe', iso2: 'ST', code: '239' },
  { icon: '🇸🇦', name: 'Saudi Arabia', iso2: 'SA', code: '966' },
  { icon: '🇸🇳', name: 'Senegal', iso2: 'SN', code: '221' },
  { icon: '🇷🇸', name: 'Serbia', iso2: 'RS', code: '381' },
  { icon: '🇸🇨', name: 'Seychelles', iso2: 'SC', code: '248' },
  { icon: '🇸🇱', name: 'Sierra Leone', iso2: 'SL', code: '232' },
  { icon: '🇸🇬', name: 'Singapore', iso2: 'SG', code: '65' },
  { icon: '🇸🇽', name: 'Sint Maarten (Dutch part)', iso2: 'SX', code: '1-721' },
  { icon: '🇸🇰', name: 'Slovakia', iso2: 'SK', code: '421' },
  { icon: '🇸🇮', name: 'Slovenia', iso2: 'SI', code: '386' },
  { icon: '🇸🇧', name: 'Solomon Islands', iso2: 'SB', code: '677' },
  { icon: '🇸🇴', name: 'Somalia', iso2: 'SO', code: '252' },
  { icon: '🇿🇦', name: 'South Africa', iso2: 'ZA', code: '27' },
  {
    icon: '🇬🇸',
    name: 'South Georgia and the South Sandwich Islands',
    iso2: 'GS',
    code: '500',
  },
  { icon: '🇸🇸', name: 'South Sudan', iso2: 'SS', code: '211' },
  { icon: '🇪🇸', name: 'Spain', iso2: 'ES', code: '34' },
  { icon: '🇱🇰', name: 'Sri Lanka', iso2: 'LK', code: '94' },
  { icon: '🇸🇩', name: 'Sudan', iso2: 'SD', code: '249' },
  { icon: '🇸🇷', name: 'Suriname', iso2: 'SR', code: '597' },
  { icon: '🇸🇯', name: 'Svalbard and Jan Mayen', iso2: 'SJ', code: '47' },
  { icon: '🇸🇿', name: 'Swaziland', iso2: 'SZ', code: '268' },
  { icon: '🇸🇪', name: 'Sweden', iso2: 'SE', code: '46' },
  { icon: '🇨🇭', name: 'Switzerland', iso2: 'CH', code: '41' },
  { icon: '🇸🇾', name: 'Syrian Arab Republic', iso2: 'SY', code: '963' },
  { icon: '🇹🇼', name: 'Taiwan', iso2: 'TW', code: '886' },
  { icon: '🇹🇯', name: 'Tajikistan', iso2: 'TJ', code: '992' },
  { icon: '🇹🇭', name: 'Thailand', iso2: 'TH', code: '66' },
  { icon: '🇹🇱', name: 'Timor-Leste', iso2: 'TL', code: '670' },
  { icon: '🇹🇬', name: 'Togo', iso2: 'TG', code: '228' },
  { icon: '🇹🇰', name: 'Tokelau', iso2: 'TK', code: '690' },
  { icon: '🇹🇴', name: 'Tonga', iso2: 'TO', code: '676' },
  { icon: '🇹🇹', name: 'Trinidad and Tobago', iso2: 'TT', code: '1-868' },
  { icon: '🇹🇳', name: 'Tunisia', iso2: 'TN', code: '216' },
  { icon: '🇹🇷', name: 'Turkey', iso2: 'TR', code: '90' },
  { icon: '🇹🇲', name: 'Turkmenistan', iso2: 'TM', code: '993' },
  { icon: '🇹🇨', name: 'Turks and Caicos Islands', iso2: 'TC', code: '1-649' },
  { icon: '🇹🇻', name: 'Tuvalu', iso2: 'TV', code: '688' },
  { icon: '🇺🇬', name: 'Uganda', iso2: 'UG', code: '256' },
  { icon: '🇺🇦', name: 'Ukraine', iso2: 'UA', code: '380' },
  { icon: '🇦🇪', name: 'United Arab Emirates', iso2: 'AE', code: '971' },
  { icon: '🇬🇧', name: 'United Kingdom', iso2: 'GB', code: '44' },
  { icon: '🇹🇿', name: 'United Republic of Tanzania', iso2: 'TZ', code: '255' },
  { icon: '🇺🇲', name: 'United States', iso2: 'US', code: '1', suggested: true },
  { icon: '🇺🇾', name: 'Uruguay', iso2: 'UY', code: '598' },
  { icon: '🇻🇮', name: 'US Virgin Islands', iso2: 'VI', code: '1-340' },
  { icon: '🇺🇿', name: 'Uzbekistan', iso2: 'UZ', code: '998' },
  { icon: '🇻🇺', name: 'Vanuatu', iso2: 'VU', code: '678' },
  { icon: '🇻🇪', name: 'Venezuela', iso2: 'VE', code: '58' },
  { icon: '🇻🇳', name: 'Vietnam', iso2: 'VN', code: '84' },
  { icon: '🇼🇫', name: 'Wallis and Futuna', iso2: 'WF', code: '681' },
  { icon: '🇪🇭', name: 'Western Sahara', iso2: 'EH', code: '212' },
  { icon: '🇾🇪', name: 'Yemen', iso2: 'YE', code: '967' },
  { icon: '🇿🇲', name: 'Zambia', iso2: 'ZM', code: '260' },
  { icon: '🇿🇼', name: 'Zimbabwe', iso2: 'ZW', code: '263' },
];
