version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - ~/local-volume/mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mailer:
    image: namshi/smtp
    restart: always

  app:
    image: covid_19_tracker:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "./wrapperScript.sh"
    depends_on:
      - mongo
      - mailer
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: covid19-api.codegoodworks.co.uk
    volumes:
      - ~/local-volume/logs:/usr/src/app/logs

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/nginx/default_location:/etc/nginx/vhost.d/default_location
    environment:
      DEFAULT_HOST: covid19-api.codegoodworks.co.uk
    depends_on:
      - app

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:0.7.0
    environment:
      SCRAPE_URI: http://nginx-proxy/stub_status
    expose:
      - '9113'
    depends_on:
      - nginx-proxy

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - nginx-prometheus-exporter

  grafana:
    image: grafana/grafana
    environment:
      VIRTUAL_HOST: monitoring.codegoodworks.co.uk
    volumes:
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  prometheus-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ygou/monitoring/prometheus-data
  grafana-storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ygou/monitoring/grafana-storage
