version: '3'

services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - ~/local-volume/mongo-data:/data/db

  app:
    image: covid_19_tracker:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ~/local-volume/logs:/usr/src/app/logs
