version: '3.4'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: covid19-api.codegoodworks.co.uk

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - ~/local-volume/mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mailer:
    image: namshi/smtp
    restart: always

  app:
    image: covid_19_tracker:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "./wrapperScript.sh"
    ports:
      - '3000'
    depends_on:
      - mongo
      - mailer
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: covid19-api.codegoodworks.co.uk
    volumes:
      - ~/local-volume/logs:/usr/src/app/logs
